### ISSUE TITLE
Scale Animation on Toggle

### ISSUE THREAD

**Issue by samyogdhital** [envless/envless#107]
https://user-images.githubusercontent.com/91406792/219126080-e15d5438-9aba-4df8-99a0-480272660272.mp4

How is this small UI tweak @dahal ?  If good then I can submit a PR.

**Comment by dahal** [comment]
Nice, I love the animation. But let's not change the colors.

**Comment by samyogdhital** [comment]
Sure. Lets keep the animation. Looks more interactive!

**Comment by dahal** [comment]
This is close in #111
