### ISSUE TITLE
Help us with translations 🌏 🌍 🌎 

### ISSUE THREAD

**Issue by dahal** [envless/envless#117]
# 🇺🇸 🇬🇧 🇨🇦 🇦🇺 
Please help us translate to your local language. Pickup the language you would like to translate, leave a comment and open an issue about the language you would like to translate. If you recommend any other languages, please comment below.

# 🇨🇳 🇹🇼 
请帮助我们将此翻译成您当地的语言。选择您想要翻译的语言，留下评论并打开关于您想要翻译的语言的问题。

# 🇦🇷 🇧🇴 🇨🇱 🇨🇴 🇨🇷 🇨🇺 🇩🇴 🇪🇨 🇸🇻 🇬🇶 🇬🇹 🇭🇳 🇲🇽 🇳🇮 🇵🇦 🇵🇾 🇵🇪 🇵🇷 🇪🇸 🇺🇾 🇻🇪 
Por favor, ayúdenos a traducir al idioma local. Elija el idioma que le gustaría traducir, deje un comentario y abra un problema sobre el idioma que le gustaría traducir.

# 🇦🇴 🇧🇷 🇨🇻 🇹🇱 🇬🇶 🇬🇼 🇲🇿 🇵🇹 🇸🇹 
Por favor, ajude-nos a traduzir para o seu idioma local. Escolha o idioma que você gostaria de traduzir, deixe um comentário e abra uma questão sobre o idioma que você gostaria de traduzir.

# 🇧🇪 🇧🇯 🇧🇫 🇧🇮 🇨🇲 🇨🇦 🇨🇫 🇹🇩 🇰🇲 🇨🇬 🇨🇩 🇨🇮 🇫🇷 🇬🇦 🇬🇳 🇭🇹 🇱🇺 🇲🇬 🇲🇱 🇲🇨 🇳🇪 🇷🇼 🇸🇳 🇸🇨 🇨🇭 🇹🇬 🇻🇺
S'il vous plaît, aidez-nous à traduire dans votre langue locale. Choisissez la langue que vous souhaitez traduire, laissez un commentaire et ouvrez une demande concernant la langue que vous souhaitez traduire.

# 🇩🇿 🇧🇭 🇰🇲 🇩🇯 🇪🇬 🇮🇶 🇯🇴 🇰🇼 🇱🇧 🇱🇾 🇲🇷 🇲🇦 🇴🇲 🇵🇸 🇶🇦 🇸🇦 🇸🇴 🇸🇩 🇸🇾 🇹🇳 🇦🇪 🇾🇪 
يرجى مساعدتنا في الترجمة إلى لغتك المحلية. اختر اللغة التي تريد ترجمتها ، واترك تعليقًا وافتح مشكلة بشأن اللغة التي تريد ترجمتها.

# 🇮🇳 
कृपया हमें अपनी स्थानिक भाषा में अनुवाद करने में सहायता करें। आप जिस भाषा का अनुवाद करना चाहें, उसे चुनें, एक टिप्पणी छोड़ें और उस भाषा के बारे में एक मुद्दा खोलें जिसे आप अनुवाद करना चाहते हैं।

**Comment by himanshu1221** [comment]
could you please assign this task to me I wanna work on this issue i work on this issue

**Comment by dahal** [comment]
Thanks @lucasguiss we would love that. We currently do not have i18n library setup as well. Would you like to start by setting up [i18next/next-i18next](https://github.com/i18next/next-i18next). We are also active on discord/slack (#translation channel) for real time conversation.

* [Join us on Slack](https://dub.sh/envless-slack)
* [Join us on Discord](https://dub.sh/envless-discord)

**Comment by Aju100** [comment]
Missing @dahal Nepali here

**Comment by dahal** [comment]
Closing this because this is not a priority for now, we will re-open an issue or create a new one in future.
