### ISSUE TITLE
[DOCS]: Update the readme 

### ISSUE THREAD

**Issue by money8203** [envless/envless#118]
**Is your feature request related to a problem? Please describe.**
Readme section seems not too descriptive

**Describe the solution you'd like**
We can add tech stacks on the readme so that people can know which tech stack this project is build upon and in which field they can contribute to it

**Comment by dahal** [comment]
Happy to take a PR on this 😍

**Comment by kumarankit999** [comment]
Can I do something here ,If you assign me

**Comment by dahal** [comment]
Sure @kumarankit999 please feel free to send a PR

**Comment by kumarankit999** [comment]
I have Sended a PR

**Comment by dahal** [comment]
thanks @kumarankit999 i have reviewed and left some comments on your PR.

**Comment by kumarankit999** [comment]
Now,You Can check once

**Comment by kumarankit999** [comment]
Ya, I Will check
