### ISSUE TITLE
[DOCS]: Improve the contributing guide

### ISSUE THREAD

**Issue by money8203** [envless/envless#119]
**Describe the bug**
Contributors section in the contributing.md file should looks good if it was in the end.

**To Reproduce**
Go to https://github.com/envless/envless/blob/main/CONTRIBUTING.md ->remove/cut the contributors part and paste it in the end

**Expected behavior**
Instead of being at the 4rd last place the contributor section will be displayed in the end

**Screenshots**
![Screenshot (224)](https://user-images.githubusercontent.com/89864818/219968139-a1156287-72b7-4447-83f6-0d3205865fbf.png)

**Comment by dahal** [comment]
Thanks @money8203 , please feel free to send a PR
