### ISSUE TITLE
[Bug] Discord Invite

### ISSUE THREAD

**Issue by himanshu1221** [envless/envless#126]
**Describe the bug**
Discord invite link is not working 

**To Reproduce**
1. Go to 'readme'
2. Click on 'join our dicord community'

**Expected behavior**
It should give us an appropiate discord invite

**Screenshots**

![Screenshot from 2023-02-21 14-43-17](https://user-images.githubusercontent.com/32031706/220300896-eee66094-9a8b-4778-80f4-d62ddede81b3.png)

**Desktop (please complete the following information):**

 - Browser-chrome
 - version - 110.0.5481.104

**Comment by chetannn** [comment]
Thanks for pointing it out. Will change it soon
