### ISSUE TITLE
[Docs] README.md

### ISSUE THREAD

**Issue by himanshu1221** [envless/envless#127]
**Is your feature request related to a problem? Please describe.**

I was finding the contrubuting.md section in readme so that how one can start contributing in this project but wasnt able to find it.In the end i founded that is is available in the **contributors** section 

**Describe the solution you'd like**

We can have a seperate section which consist of contributing guidlines and code of coduct so it would be much easier to understand the guidelines 

**Describe alternatives you've considered**

we will  update the readme and will add  a seperate section for the same

**Additional context**

<h2>This is how it looks now</h2>

![Screenshot from 2023-02-21 15-06-18](https://user-images.githubusercontent.com/32031706/220307993-73a23efe-2d5c-4953-8372-4b73dbb89593.png)

<h2>This is how we can make it more informative</h2>

![Screenshot from 2023-02-21 15-13-03](https://user-images.githubusercontent.com/32031706/220308297-654d9a5e-0170-404f-8730-860f8950147f.png)

**Comment by money8203** [comment]
Thanks for raising the issue Himanshu! 

I feel like contributors section should be there as it is as it shows our contributors. Instead we can add another section on the front page of readme named as "contributing" and there we can add these points you mentioned.

**Comment by dahal** [comment]
Thanks for opening this issue @himanshu1221 and please send a PR. I have assigned this to you.
