### ISSUE TITLE
[DOCS] Update readme

### ISSUE THREAD

**Issue by Collins-Omariba** [envless/envless#128]
**Is your feature request related to a problem? Please describe.**

The description section of <strong>.envless</strong>  on the readme 
 - An open-source, frictionless and secure way to share and manage app secrets across team.

**Describe the solution you'd like**

I think the correct description should be <strong>teams</strong> at the end as below
 - An open-source, frictionless and secure way to share and manage app secrets across teams.

**Comment by chetannn** [comment]
Oh. That's the typo. Let me fix it.
