### ISSUE TITLE
Improving the README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [envless/envless#132]
I suggest :
+  adding a description section containing a short paragraph describing the site/project
+ adding cool icons for Discord and Slack invites

Note:
**If the authors like the suggestions, I would like to work on this issue and send a PR**

**Comment by dahal** [comment]
Hey @the-amazing-atharva thanks for creating this issue. We definitely would love some icon/banner for slack & discord invite links. Adding a description is also another good suggestion. Curious what you have in mind? Please feel free to join slack/discord so we can discuss there real-time.

**Comment by the-amazing-atharva** [comment]
Thanks for the reply!

Looking forward for the discussions
Is ok if I send a screenshot of the work here for easier  access for me and I can edit based on your suggestions?

**Comment by dahal** [comment]
Sure thing, please attach them here.

**Comment by the-amazing-atharva** [comment]
### Note :
I am currently a beginner in development and have no idea beyond HTML, CSS so wrote a general description for the repository based on keywords. Do let me know if I should add/delete any statement 

### Thoughts?
![image](https://user-images.githubusercontent.com/121221252/220575329-91aa4afa-4898-4b9f-90ce-34ecbe82d926.png)

**Comment by the-amazing-atharva** [comment]
Thank you so much for the reply!!!
It means a lot 😄 

Do I send a PR or are there any changes?

**Comment by dahal** [comment]
One quick suggestion, please replace .envless with Envless. And if you could make that table a full width, and add these icons instead, that would be great

* https://worldvectorlogo.com/logo/slack-2
* https://worldvectorlogo.com/logo/discord-wordmark-1

Also, please download to svg files to .github/images folders and link them from there (just incase the file/url changes on external site)

I also see you are a Canva designer, if you can be creative with banners, thats even better. Its time for you to shine 🌟

Something like this would be amazing
* https://static-prod.adweek.com/wp-content/uploads/2022/10/Discord-Banner-1-1500x680.png

And similar for slack, that would fit on two column in a table (full width).

Please note that this is going above and beyond if you want to be creative, else, it LGTM.

**Comment by the-amazing-atharva** [comment]
> One quick suggestion, please replace .envless with Envless. And if you could make that table a full width, and add these icons instead, that would be great
> 
> * https://worldvectorlogo.com/logo/slack-2
> * https://worldvectorlogo.com/logo/discord-wordmark-1
> 
> Also, please download to svg files to .github/images folders and link them from there (just incase the file/url changes on external site)
> 
> I also see you are a Canva designer, if you can be creative with banners, thats even better. Its time for you to shine 🌟
> 
> Something like this would be amazing
> 
> * https://static-prod.adweek.com/wp-content/uploads/2022/10/Discord-Banner-1-1500x680.png
> 
> And similar for slack, that would fit on two column in a table (full width).
> 
> Please note that this is going above and beyond if you want to be creative, else, it LGTM.

Done!
Working on it in sometime

**Comment by the-amazing-atharva** [comment]
Just sent a PR to add images to the folder to use in the README

Will make necessary changes after it gets merged so that the directory is `envless/envless` and not my fork

**Comment by the-amazing-atharva** [comment]
Found some official slack banner like the discord one.

**Thoughts?**
![2019-03_Haughey_SlackGuide3_Unfurl](https://user-images.githubusercontent.com/121221252/220592486-ae6685e8-ac34-4c01-a049-e633c8fe4af3.png)
.
.
![2019-02_Haughey_SlackGuide1_Unfurl](https://user-images.githubusercontent.com/121221252/220592617-4bca3ac4-8739-46ed-8a2a-ce176f1a279f.jpg)
.
.
![2020-01_Haughey_JustJoinedSlack_Unfurl](https://user-images.githubusercontent.com/121221252/220592679-314c815e-ac2f-4dc5-b9a9-0d0f18504729.jpg)
.
.

![2021-02-haughey-get-started-slack-connect-unfurl](https://user-images.githubusercontent.com/121221252/220592752-1d3925db-b414-4d0b-81ad-505531497b0b.jpg)

.
.
![slack-connect-xero-boldstart-venture-segment-unfurl](https://user-images.githubusercontent.com/121221252/220592975-1bba213a-2161-4ae0-949d-50405143d250.jpg)

.
.
![unfurl](https://user-images.githubusercontent.com/121221252/220593040-465f3fa6-5786-4ecd-af26-cd095352cd4f.jpg)

.
.

**Comment by dahal** [comment]
Love it, Lets go with this one

![](https://user-images.githubusercontent.com/121221252/220593040-465f3fa6-5786-4ecd-af26-cd095352cd4f.jpg)

**Comment by money8203** [comment]
Awesome work @the-amazing-atharva 

How about if you could make the discord and slack icons placed vertically. That'd look more awesome!

**Comment by the-amazing-atharva** [comment]
> Love it, Lets go with this one
> 
> ![](https://user-images.githubusercontent.com/121221252/220593040-465f3fa6-5786-4ecd-af26-cd095352cd4f.jpg)

Sure I'll add this banner and the banner above for discord too
But for that I will have to add those images in this repository right?
Do I make a new branch for that or send a new PR?

**Comment by the-amazing-atharva** [comment]
> Awesome work @the-amazing-atharva
> 
> How about if you could make the discord and slack icons placed vertically. That'd look more awesome!

Vertically as in?
Currently, I will be adding rectangular banners

**Comment by money8203** [comment]
By placing the discord and slack icon in the silly diagrams I just draw, and not in the table format

![Screenshot (229)1](https://user-images.githubusercontent.com/89864818/220830368-f4e8b64a-f141-4fa3-89bc-72607ac5e45c.png)

**Comment by the-amazing-atharva** [comment]
> By placing the discord and slack icon in the silly diagrams I just draw, and not in the table format
> 
> I think you got the jist of it!
> 
> ![Screenshot (229)1](https://user-images.githubusercontent.com/89864818/220830368-f4e8b64a-f141-4fa3-89bc-72607ac5e45c.png)

Yup got it
Posting screenshot soon

**Comment by the-amazing-atharva** [comment]
thoughts @money8203 @dahal 

![image](https://user-images.githubusercontent.com/121221252/220832240-03340678-8224-447e-8f57-bd1fae118722.png)

**Comment by money8203** [comment]
looks good, try to reduce their size and maybe remove the click below button!
What do you think @dahal

**Comment by dahal** [comment]
I like it, and i agree to Manish. Lets remove click below button and we should be good to go.

**Comment by the-amazing-atharva** [comment]
Making the changes !

**Comment by the-amazing-atharva** [comment]
**Update :**
@dahal , @money8203 

![image](https://user-images.githubusercontent.com/121221252/221072884-76730714-262c-4443-9c8c-2004f6fbf747.png)

**Comment by dahal** [comment]
> **Update :** @dahal , @money8203
> 
> ![image](https://user-images.githubusercontent.com/121221252/221072884-76730714-262c-4443-9c8c-2004f6fbf747.png)

😍

**Comment by money8203** [comment]
Great work @the-amazing-atharva!

**Comment by the-amazing-atharva** [comment]
Sending a PR
