### ISSUE TITLE
Remove `unstable_getserversession` usage from utils/session.ts

### ISSUE THREAD

**Issue by chetannn** [envless/envless#143]
As `unstable_getserversession` has been renamed to `getServerSession`. We can start using that.

https://next-auth.js.org/configuration/nextjs#unstable_getserversession

**Comment by chetannn** [comment]
Here is the changelog for this in `next-auth` package
https://github.com/nextauthjs/next-auth/compare/next-auth@4.18.10...next-auth@4.19.0

**Comment by dahal** [comment]
Fixed on #143
