### ISSUE TITLE
[BUG] Navbar covering the request access card

### ISSUE THREAD

**Issue by himanshu1221** [envless/envless#150]
**Describe the bug**

When i clicked on the documentation request access card opened and the top part of the card was under the navbar

**To Reproduce**
1. Go to 'envless.dev'
2. Click on 'Documentation'
3. On the top 'half part of logo is covered under the navbar '

**Expected behavior**

navbar should not cover the card

**Screenshots**

![Screenshot from 2023-02-27 11-44-08](https://user-images.githubusercontent.com/32031706/221489377-d398e7df-d90a-4106-90cc-5f6a68f09a68.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [Chrome]
 - Version [110.0.5481.177]

**Additional context**

<h3>Please Review the issue and if you find this valid enough I would like to work on this issue please assign it to me </h3>

**Comment by dahal** [comment]
@himanshu1221 thanks for reporting this issue. Fixes for this should go to [prelaunch](https://github.com/envless/envless/tree/prelaunch) branch

**Comment by himanshu1221** [comment]
> @himanshu1221 thanks for reporting this issue. Fixes for this should go to [prelaunch](https://github.com/envless/envless/tree/prelaunch) branch

I am on it !

**Comment by himanshukrmr** [comment]
Hi @dahal if the issue still open I would like to try this.

**Comment by dahal** [comment]
@himanshu1221 @himanshukrmr that prelaunch is a temp page and will be replaced with the correct page on `main` soon once we release. Not a priority right now. I will mark this as `wontfix`. Please feel free to pick up other issues.
