### ISSUE TITLE
Replace `react-hot-toast` with `@zag-js/toast`

### ISSUE THREAD

**Issue by chetannn** [envless/envless#171]
As we are unable to click on any part of the application because `react-hot-toast` renders on the top of every element with higher z-index. `@zag-js/toast` will be the solution as it it renders to portal and has nice API to work with.

**Comment by Jittojoyes98** [comment]
Can i work on this ?

**Comment by dahal** [comment]
Sure thing @Jittojoyes98 , please confirm when you pick this up and we can assign it to you.

**Comment by chetannn** [comment]
Sure.. Go ahead 🚀

**Comment by chetannn** [comment]
Just remember that. Make a separate component that uses `@zag-js/toast` so that it will be easier for us to fallback.

**Comment by Jittojoyes98** [comment]
Sure will ping on slack.Let me check with the codebase

**Comment by dahal** [comment]
Hi @Jittojoyes98 I have assigned this issue to you. Please feel free to submit the PR when you are ready. 🙌🏼

**Comment by YuvrajPraveenSingh** [comment]
Is this issue open

**Comment by YuvrajPraveenSingh** [comment]
@chetannn @dahal is tis open

**Comment by chetannn** [comment]
Hello there, @YuvrajPraveenSingh
Welcome to Envless. I am glad that you are interested in solving this issue. Currently we have assigned this issue to @Jittojoyes98. You can check other issues as well 🙂

**Comment by dahal** [comment]
I did not see any promising outcome on this issues, with that, I am going to un-assign @Jittojoyes98 , please let me know if you would like to take this @YuvrajPraveenSingh

**Comment by YuvrajPraveenSingh** [comment]
@dahal i would like to take this issue

**Comment by dahal** [comment]
Sure thing @YuvrajPraveenSingh, I have assigned it to you.

**Comment by YuvrajPraveenSingh** [comment]
@dahal @chetannn  hi there,  thanks for assigning it to me .

I have not worked with these two libs before so, is it all right if I ask something here and there for you on the things I don't get right away?

**Comment by dahal** [comment]
@YuvrajPraveenSingh sure thing. Also please join our discord/slack channel for immediate response. We are pretty active there and get back to you right away, if we are around. Links are on readme.
