### ISSUE TITLE
Fix avatar on member's  table

### ISSUE THREAD

**Issue by dahal** [envless/envless#184]
### Describe the bug
Avatar link is broken on member's table

### To Reproduce
1. Run the seed file `yarn db:seed`
1. Go to `/projects/[:id]/members` after you login
1. You will see members table without avatar
1. Toggle between active, pending and inactive, avatar is broken there as well.

### Expected behavior
Current member table does not render the avatar, we can use gravatar and default to [vercel's avatar endpoint](https://avatar.vercel.sh/)

### Screenshots
![Xnapper-2023-03-04-02 53 24](https://user-images.githubusercontent.com/3684236/222886795-6a8178b4-57a6-4882-85bf-8afb8ee01dbf.png)

**Comment by harshith-venkatesh** [comment]
Hi @dahal , I would like to look into this issue, 
Is the expectation to see for error in rendering the avatar and onError replace the avatar with the one available through Vercel?

**Comment by dahal** [comment]
Yes thats correct @harshith-venkatesh its not rendering the avatar correctly right now. We just need to make it work with vercel's avatar (like your profile avatar on top right corner)

Thanks for your interest, I have assigned the issue to you. Please feel free to submit a PR when you are ready 🚀

**Comment by dahal** [comment]
How is the progress @harshith-venkatesh ?
