### ISSUE TITLE
Update or delete member

### ISSUE THREAD

**Issue by dahal** [envless/envless#185]
### Problem
Currently you cannot change member's role or remove them from the project.

### Solution
* Run the seed file `yarn db:seed`
* Go to `projects/:id/members` page
* Select active tab
* Click on the settings icon
* Open a modal with select input (current role selected by default)
* Have two buttons, one to remove member another one to save and close the modal.
* Allow only `owner` and `maintainer` to make this change.
* When you click on remove member, do not delete the member, but set `access.active` to `false`

**Comment by ttebify** [comment]
Hi @dahal, I can work on implementing this feature

**Comment by dahal** [comment]
Please go ahead @ttebify , I have assigned it to you. ✅

**Comment by dahal** [comment]
> Hi @dahal, I can work on implementing this feature

Please go ahead @ttebify , I have assigned it to you. ✅

**Comment by ttebify** [comment]
I think this issue is done and should be closed
