### ISSUE TITLE
Render invitation expired status and re-invite pending user, if they invitation expired

### ISSUE THREAD

**Issue by dahal** [envless/envless#186]
### Problem
Currently you cannot re-invite pending user, if their invite link has expired. Note: invite link expires after 48 hours for security.

### Solution
* Run the seed file `yarn db:seed`
* Go to `projects/:id/members` page
* Select `pending` tab
* Implement `expired` feature (if user has not accepted invitation within 48 hours, the link expires)
* Replace the settings icon with re-invite icon (we using [lucide](https://lucide.dev/icon/mail-check?search=email) icon set and we can use `MailCheck` icon for this. When you hover over the icon, show a tooltip, we have balloon.css for simple tooltip like this.

Here is the usecase

```tsx
<MainCheck aria-label="Re-invite member" data-balloon-pos="up" />
```
* If the invitation link has not expired yet, render delete icons with, when clicked should delete the invite record (for security)

**Comment by ttebify** [comment]
I can work on this one 🚀

**Comment by dahal** [comment]
> I can work on this one 🚀

Lets go 🚀
