### ISSUE TITLE
Re-activate inactive users

### ISSUE THREAD

**Issue by dahal** [envless/envless#188]
### Problem
Currently you cannot re-activate members in `inactive` tab

### Solution
* Run the seed file `yarn db:seed`
* Go to `projects/:id/members` page
* Select `inactive` tab, you will see some members
* When you hover over the settings icon, show a tooltip, you can use balloon.css for tooltip (already on the project for this and here is the use case)

```tsx
<Settings2 aria-label="Re-activate member" data-balloon-pos="up" />
```

* When you click on this, set `access.active` status to `true`
* Only project `owner` and/or `maintainer` should have access to this

**Comment by laasem** [comment]
Hi @dahal, I can work on this.

**Comment by dahal** [comment]
Hi @laasem , welcome to Envless. I am glad you are interested in solving this issue. I have assigned it to you. Please submit the PR when ready. 🙌🏼

**Comment by dahal** [comment]
Hi @laasem is there any update? Please let us know so we can prioritize other dependent tasks as accordingly. We may have to re-open for others to contribute if we dont get any response from you.

**Comment by laasem** [comment]
Hi @dahal, apologies for the lack of communication. Unfortunately I'll no longer be able to pick it up. Please feel free to un-assign me.

**Comment by dahal** [comment]
This is issue is open for anyone to pickup.

**Comment by ttebify** [comment]
I can work on this feature
