### ISSUE TITLE
Show a confirmation modal before deleting the project

### ISSUE THREAD

**Issue by dahal** [envless/envless#189]
Problem
---
We currently do not ask for a confirmation before deleting the project.

Solution
---

* Run the seed file `yarn db:seed`
* Go to `projects/:id/settings/danger` page
* Click on the `Delete the project` button.
* That deletes the project entirely
* Instead, show them a confirmation modal, where they have to type in the exact project name before they delete the project.
* If they have 2FA enabled, trigger 2FA verification.
* After this double verification, if they still want to continue, delete the project.

Screenshot
---
![image](https://user-images.githubusercontent.com/3684236/222893533-95129b1a-c5c3-425e-b695-1a5d6fc0bc4f.png)

**Comment by ttebify** [comment]
Working on this already.
