### ISSUE TITLE
feature: use project.slug instead or project.id on routes

### ISSUE THREAD

**Issue by dahal** [envless/envless#195]
## Is your feature request related to a problem? Please describe.
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Routes with long project id looks ugly.

## Describe the solution you'd like
> A clear and concise description of what you want to happen.

Add `slug` column to project table and replace all the project specific routes with `slug` instead of routes.

This issue cannot only be implemented after we corresponding issue #194 is merged.

![Dark](https://user-images.githubusercontent.com/3684236/224464228-87ebbb01-9221-4619-b8a4-b8bab4108373.png)

**Comment by ttebify** [comment]
Started working on this already.
