### ISSUE TITLE
[BUG]: Clicking on documentation button displays early access registration modal

### ISSUE THREAD

**Issue by ttebify** [envless/envless#235]
### Describe the bug

When clicking on the "Documentation" button on the `https://envless.dev/` website, instead of being taken to the documentation page, the early access registration modal is displayed. This behavior occurs even after requesting early access using the registration form.

### Steps to reproduce

1. Go to the https://envless.dev/ website
2. Click on the "Documentation" button in the navigation bar
3. The early access registration modal is displayed

### Expected behavior

Clicking on the "Documentation" button should take the user to the documentation page, not display the early access registration modal. The early access registration modal should only be displayed for users who have not yet requested early access.

**Comment by dahal** [comment]
This is intentional, for prelaunch signups. Closing it for now.
