### ISSUE TITLE
[BUG]: Remove Audit logs from /settings tab

### ISSUE THREAD

**Issue by dahal** [envless/envless#285]
### Describe the bug

If you go to `/settings` you will see Audit logs, lets get rid of it.

### Steps to reproduce

1. Fork [`envless/envless`](https://github.com/envless/envless/fork)
2. Clone the repo
3. Follow the [Contribution Guidelines](https://github.com/envless/envless/blob/main/CONTRIBUTING.md)
4. Run the seed `yarn db:seed`
5. After you login, go to `/settings` page.
6. You will see `Audit logs`, and that will result in 404

### Expected behavior

Lets just get rid of that

### Screenshots

![image](https://user-images.githubusercontent.com/3684236/227149594-95841c65-e0ad-498b-9a15-73046198c870.png)

**Comment by gustavojms** [comment]
Going to work on it right now
