### ISSUE TITLE
[FEATURE]: Create an utils for Two Factor Authentication modal

### ISSUE THREAD

**Issue by dahal** [envless/envless#311]
### Description

We currently do not have a good way to ask users to go through 2FA before they submit some mission critical forms/buttons or perform some actions.

### Possible solution

* Create a utils, called `withTwoFactorAuth`
* All the mission critical function calls are expected to be wrapped by this, for example

```ts
withTwoFactorAuth(
  deleteProject()
)
```
* Create a zustand store, called `twoFactorStore`, set the initial states `enabled | disabled | verified` based on database and redis's session. For reference
https://github.com/envless/envless/blob/a3e08de67a8f232765354e8d4ea0c48a15ce6100/apps/platform/middleware.ts#L47-L54
* Open the modal if the status is `enabled && !verified`
* Once user goes through verification, execute the original function.

**Comment by ttebify** [comment]
I can work on this one
