### ISSUE TITLE
[FEATURE]: trigger browser native confirm before allowing CLI token rotation

### ISSUE THREAD

**Issue by dahal** [envless/envless#328]
### Description

We currently do not render ask for any confirmation when user try to reset CLI token.

### Possible solution

* Fork the repo
* Clone and setup, please follow Contributing guideline on readme.
* Run the seed fine `yarn db:seed`
* Login and go to /projects
* Click on the project.
* A CLI setup slideover will appear. On 2nd step you will see Generate CLI token, click on that.
* Reload the page, you will see Rotate CLI token button (red)

Show browser native confirm popup with this message

**Are you sure you want to rotate your CLI token? All previous CLI access will be revoked. This action cannot be undone.**

### Additional information

![image](https://user-images.githubusercontent.com/3684236/229734900-1969020b-5992-47ce-b0b4-396a519840c1.png)

**Comment by ttebify** [comment]
I can work on implementing this feature
