### ISSUE TITLE
[BUG]: Hide status, sort, filter and search on EmptyState

### ISSUE THREAD

**Issue by dahal** [envless/envless#341]
### Describe the bug

We currently have `status, sort, filter and search`. They are useless when there are no branches on the table.

### Steps to reproduce

1. Fork and follow [Contributing guideline](https://github.com/envless/envless/blob/main/CONTRIBUTING.md) to setup project.
2. Run `yarn db:seed`
3. Go to `/projects` and click on a project
4. Create a new project
5. Go to `Branches` and `Pull requests` tabs
6. You see empty table with `status, sort, filter and search`

### Expected behavior

Hide those if branche.length is less less than 2, `main`. 2 because main branch is created by default and thats protected. It will not show up on this list.

#### Branches
![image](https://user-images.githubusercontent.com/3684236/230287480-34201cf3-50a9-4f6d-b42f-6e9c6fbf1e48.png)

#### Pull Requests
![image](https://user-images.githubusercontent.com/3684236/230290002-3a10e3a6-ad98-442c-b8ce-fe11c8f77c26.png)

**Comment by JMTiburcio** [comment]
Hi there!

I'm excited to make my first contribution to open source projects and have a solution for this issue. I have read the guidelines for making contributions and would like to make a pull request.

Thank you for keeping Envless as OpenSource. This helps me in my studies and I plan to make more contributions!

**Comment by JMTiburcio** [comment]
I created a conditional on the hasFilters property to be true or false depending on the size of the branches or pull request array.

![image](https://user-images.githubusercontent.com/98969322/230745128-9f8bf158-e9ee-4458-9bde-3631a0d476d1.png)

![image](https://user-images.githubusercontent.com/98969322/230745139-c2e3aafd-bbcb-436e-9985-812104914ae8.png)

![image](https://user-images.githubusercontent.com/98969322/230745147-2d0d06d2-6ebf-460e-8c74-5c41c8c173df.png)

**Comment by ttebify** [comment]
We appreciate your interest in contributing to Envless, @JMTiburcio. We look forward to seeing what else you can come up with.

Hi @dahal, a fix to this issue was merged in this PR (#343)

**Comment by dahal** [comment]
Thanks for reviewing it @ttebify and yea, looks like I missed this one.

When opening a PR, please make sure to include these text, which will automatically close associated issue.

* Fixes #341

or

* Closes #341

cc @JMTiburcio @swapnil-talpade , you can learn more about it here
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
