### ISSUE TITLE
[BUG]: replace mailing.run with `react-email`

### ISSUE THREAD

**Issue by dahal** [envless/envless#346]
### Description

Looks like `mailing.run` has so many issues, especially on windows.
* https://github.com/sofn-xyz/mailing/issues/462
* https://github.com/sofn-xyz/mailing/issues/172

### Possible solution

Lets replace it with https://react.email

This means we also have to re-design our existing email templates using tailwind.css and replace them wherever they are being used.

**Comment by chetannn** [comment]
![image](https://user-images.githubusercontent.com/22125423/230599447-bffadf2e-813b-4b0e-947e-adb1d700577c.png)
https://github.com/resendlabs/react-email/issues/634
https://github.com/resendlabs/react-email/issues/633

It looks like `resendlabs/react-email` is having problem with the latest release. I have tried the previous few versions as well. Waiting for their patch release.

**Comment by dahal** [comment]
The main reason why we explored this option was because mailing.run was having some issues on windows and wsl setup. Now that we have dockerized, this is no longer a priority. Closing it for now. We will re-visit this in future.
