### ISSUE TITLE
[BUG]: Render user friendly error message when accepting invitation

### ISSUE THREAD

**Issue by dahal** [envless/envless#348]
### Describe the bug

We are returning a raw error message when trying accept an invitation.

### Steps to reproduce

1. Fork and follow [Contributing guideline](https://github.com/envless/envless/blob/main/CONTRIBUTING.md) to setup project.
2. Run `yarn db:seed`
3. Go to `/projects` and click on a project
4. Create a project
5. Go to `Members` tab and invite a member
6. Invitation email will popup on a new tab
7. Sign-out on a previous tab
8. Go to the tab that was open on step # 6
9. Click on the button to accept invitation
10. Type in a wrong email, you will receive an error message as shown in following screenshot.

### Expected behavior

Render user friendly error message when accepting invitation

### Screenshots

![image](https://user-images.githubusercontent.com/3684236/230709668-9707d9ed-e180-4b00-aa0d-3a4888663b02.png)

**Comment by ttebify** [comment]
This issue might be fixed by this PR (#347) I noticed it while working on it.

**Comment by ttebify** [comment]
Hi @dahal Confirm that this issue is fixed

**Comment by dahal** [comment]
> Hi @dahal Confirm that this issue is fixed

Yep, looks good to me. Thanks for the reminder 🎉
