### ISSUE TITLE
Lock user account and send them an email if they fail two factor auth for too many times.

### ISSUE THREAD

**Issue by dahal** [envless/envless#38]
Implement user locking mechanism so it can be used for other security features like:-

1. If any fraudulent activity is detected.
2. User tried to DDoS
3. Others?

**Comment by harshmange44** [comment]
@dahal Hey I'd love to fix this and even contribute more in this project. Any docs to set it up locally would be appreciated.

**Comment by dahal** [comment]
Thats dope @harshmange44 

I will write a doc this weekend and add more issues. Thanks for reaching out.

**Comment by dahal** [comment]
@harshmange44 Here is the [Contributing guideline](https://github.com/envless/envless/blob/main/CONTRIBUTING.md). Please let me know if you are having any issue with the setup.

https://cal.com/dahal/30min

**Comment by dahal** [comment]
@harshmange44 is there an update on this one?

**Comment by Pratik-Mahajan257** [comment]
@dahal assign this to me

**Comment by dahal** [comment]
Its all yours, would love to see a PR soon. Please feel free to schedule a time if you like to pair with me.

https://cal.com/dahal/30min

**Comment by harshmange44** [comment]
> @harshmange44 is there an update on this one?

Yea already working on it and exploring couple of things

**Comment by dahal** [comment]
Wait are @harshmange44 and @Pratik-Mahajan257 same, regardless I would love to see wha you/both come up with.

**Comment by dahal** [comment]
I you have questions or queries about implementation detail, please fee free to schedule a time with me https://cal.com/dahal/30min

**Comment by dahal** [comment]
@harshmange44 @Pratik-Mahajan257 anybody on this one, if so can you please update the status?

**Comment by dahal** [comment]
This is open for anybody to take it.

Please let me know if you have any progress @harshmange44 @Pratik-Mahajan257 so we can avoid duplicates.

**Comment by ttebify** [comment]
I'll be willing to take this one if no one else is available to.

**Comment by dahal** [comment]
> I'll be willing to take this one if no one else is available to.

Please go ahead 👍🏼
