### ISSUE TITLE
[OTHER]: update CLI to read contents from .envless.yml

### ISSUE THREAD

**Issue by Chinedu19** [envless/envless#386]
### What would you like to share?

Currently, To update a project's information. It would be helpful if the CLI could automatically retrieve the project ID from the .envless.yml file to streamline the process and reduce the chance of errors.

### Proposed Solution:
- Add support for reading project info from .envless.yml

### Benefits:
- Streamlined workflow for the CLI users.

**Comment by dahal** [comment]
This should be resolved
https://github.com/envless/envless/blob/43c2f36fd07f0b31ffb7ed99fff538d61453b4bd/apps/cli/src/lib/dotEnvless.ts#L4-L11
