### ISSUE TITLE
[FEATURE]:  Prevent Deletion of Main Branch 

### ISSUE THREAD

**Issue by ttebify** [envless/envless#462]
### Description

Currently, our application relies on the existence of the `main` branch to function properly. If a user were to accidentally or intentionally delete the `main` branch, it could cause issues with the application. Therefore, we need to prevent users from being able to delete the `main` branch.

### Possible solution

We can implement a check to ensure that the `main` branch cannot be deleted.

1. Clone the project
2. Go to `apps/platform/trpc/branch.ts`
3. Find the delete route and add a check like the following:

```ts
if (branch.name === "main") {
        throw new TRPCError({
          code: "FORBIDDEN",
          message: "You cannot delete the main branch",
        });
      }

```
We can show an error message and prevent the deletion.

Additionally, we can add a warning message when a user attempts to remove the protection from the `main` branch, reminding them of the importance of this branch and the potential consequences of deleting it.

**Comment by chetannn** [comment]
Does this issue related to protected branch ?
Same functionality is achieved using the protected branch.

**Comment by dahal** [comment]
> 

This is for when user un-protects `main` and tries to delete it. By default we should restrict `main` deletion.
