### ISSUE TITLE
Add Footer Section

### ISSUE THREAD

**Issue by money8203** [envless/envless#464]
### Description

I have noticed that there is no footer section on the website. I believe that adding a footer section would greatly enhance the user experience and provide important information and links to users.

### Possible solution

Add a footer section that could include links to important pages, such as the contact page, about page, and social media profiles. It could also provide legal information, such as terms and conditions and privacy policy.

**Comment by dahal** [comment]
Thanks for opening this issue @money8203 , however, our current landing page is only for pre-launch. We will be re-designing the whole thing when we are ready to publish. Closing this issue for now.
