### ISSUE TITLE
[BUG]: User's full name is not being saved during signup

### ISSUE THREAD

**Issue by dahal** [envless/envless#473]
### Describe the bug

User's full name is not being saved during signup process.

### Steps to reproduce

* Setup project by following contributing guideline.
* Go to signup page `/signup`
* Signup with new email and full name
* Go to `/settings` page after successful signup
* Sometimes full names are not saved. 

### Expected behavior

Save user's full name during signup process.

**Comment by horrificCoder** [comment]
@dahal Can I work on this?

**Comment by dahal** [comment]
I am currently working on changing our signup flow, that should either fix or the flow will change. I am going to tag this issue as blocked for time being and will revisit after new signup flow is merged. Feel free to pick other issue. Also, please [join our discord](https://dub.sh/envless-discord) for real time conversation on issues and PRs.

**Comment by dahal** [comment]
This issue has been fixed by #504

@horrificCoder I have added new set of issues and would really appreciate some help. Please feel free to claim them and I will assign them to you.
