### ISSUE TITLE
[BUG]: Tooltip on the protected branch table is broken, we could use some design help there as well.

### ISSUE THREAD

**Issue by dahal** [envless/envless#510]
### What would you like to share?

As you can see the screenshots below, the tooltips are broken. The table also looks out of place. Would love some design help here.

### Additional information

Screenshots
---
![Screen Shot 2023-06-07 at 12 33 19 AM](https://github.com/envless/envless/assets/3684236/1329270c-38af-4ff1-b2db-2189b7de30ca)

Projected branches table
---
![Screen Shot 2023-06-07 at 12 33 28 AM](https://github.com/envless/envless/assets/3684236/a4c0b8c0-11fe-4ecc-aefa-60e40f3997a8)

**Comment by qutluq** [comment]
@dahal please assign this issue to me.
