### ISSUE TITLE
[BUG]: Branch selector on protected branch page could use some design and UX improvement

### ISSUE THREAD

**Issue by dahal** [envless/envless#511]
### What would you like to share?

The input after selecting branch is not quite appealing. Would love some ideas and help on this.

### Additional information

![Screen Shot 2023-06-07 at 12 36 15 AM](https://github.com/envless/envless/assets/3684236/41348791-347c-4f75-8d72-ce87a80b3d63)

**Comment by qutluq** [comment]
@dahal please assign this issue to me.
