### ISSUE TITLE
[FEAT]: Add email below names on the Audit table.

### ISSUE THREAD

**Issue by dahal** [envless/envless#514]
### What would you like to share?

Audit table does not currently have email, just name. Lets add email below the name as well.

**Comment by qutluq** [comment]
Hi, please assign this issue to me.

**Comment by dahal** [comment]
> Hi, please assign this issue to me.

@qutluq As you can see right above your comment, @swapnil-talpade has already taken care of this one. Could you pick another one 🙏🏼

**Comment by qutluq** [comment]
@dahal sorry didn't notice it. Will choose another one.
