### ISSUE TITLE
[FEAT]: Make audit table searchable by name/email and/or action

### ISSUE THREAD

**Issue by dahal** [envless/envless#515]
### What would you like to share?

Its not currently searchable, we can start by implementing client side search. We already have `fuse.js` and some implementation example on our codebase. Please take a look at them.

**Comment by qutluq** [comment]
@dahal please assign this issue to me.

**Comment by qutluq** [comment]
@dahal can I ask you to make it clear, what do you mean by "or action" option? Does it mean that it must search only action column so that user somehow chooses what columns to search?

**Comment by qutluq** [comment]
@dahal, could you please clarify the meaning of the "or action" option? Should users be able to select from a list of columns to search before performing the search?

**Comment by swapnil-talpade** [comment]
> @dahal, could you please clarify the meaning of the "or action" option? Should users be able to select from a list of columns to search before performing the search?

so there are branch created, project created, access created etc actions user should be able to search within these actions, you can refer `auditActions.ts` file for more

**Comment by qutluq** [comment]
@swapnil-talpade sorry for the confusion, I meant the following: at the moment in my code the columns to be searched are "createdBy.name", "createdBy.email", and"action". Everything works OK. But I was wondering if there must be the possibility of searching only the "action" column, ignoring "createdBy.name", "createdBy.email" columns. From the title I can see that there must be three options for the columns to be searched:
1) "createdBy.name", "createdBy.email", and"action"
2) "createdBy.name", "createdBy.email", or "action" which in its turn gives two options:
  2.a) "createdBy.name", "createdBy.email"
  2.b) "action"

**Comment by qutluq** [comment]
@dahal, @swapnil-talpade  The PR is ready, what if I push it, so that you can review the code? Maybe I am overthinking the situation and unnecessarily causing any inconvenience.

**Comment by dahal** [comment]
> @dahal, @swapnil-talpade The PR is ready, what if I push it, so that you can review the code? Maybe I am overthinking the situation and unnecessarily causing any inconvenience.

@qutluq the bare minimum solution should be good enough for now. On our V2 release, we will have advanced filter option where users can filter and search by column. Please feel free to submit the PR.
