### ISSUE TITLE
Project settings page

### ISSUE THREAD

**Issue by dahal** [envless/envless#72]
Project settings page should include:-

* Updating project name
* Setting up protected branches
    * Developers can setup multiple protected branches (eg: `main`, `staging`, `development` etc), you can think of these branches as environments.
    * When developer works on a feature/fix/chore locally, they can branch out of `development` branch for example.

**Comment by samyogdhital** [comment]
@dahal Currently working UI.

**Comment by dahal** [comment]
I think this is mostly done, second bullet point will be continued on cli works
