### ISSUE TITLE
Help us write tests 🎖️

### ISSUE THREAD

**Issue by dahal** [envless/envless#76]
- [ ] Setup and configure vitest for unit testing
- [ ] Setup and configure playwright / cypress for e2e testing (not sure which one to go with)
- [ ] Write tests for existing utils/libs/trpcs/models and components

**Comment by chetannn** [comment]
Need to research... 👀

**Comment by samyogdhital** [comment]
@dahal Do we need to setup cypress ?

**Comment by dahal** [comment]
@samyogdhital yes, we need help with both unit and e2e tests and lets go with:-

* Cypress for E2E testing
* Jest with React Testing Library for Unit testing

This might come handy during the setup and writing tests
https://nextjs.org/docs/testing

We are on discord, please join us https://discord.gg/3H4xkDDwWj

**Comment by samyogdhital** [comment]
@dahal great cypress on the line after that lets work with jest

**Comment by samyogdhital** [comment]
We are done with cypress setup, the test case for login flow is remaining. Currently I am working on setting up jest for unit testing. Will submit a pr when done!
