### ISSUE TITLE
[FEATURE]: Pull Request Template

### ISSUE THREAD

**Issue by money8203** [envless/envless#93]
Pull request templates are great to have so that we could get a better gist of what people have to propose

**Comment by dahal** [comment]
I agree, I would love to see some example projects with nice PR templates, please share them and submit pull request as well 🙏🏼

**Comment by dahal** [comment]
I have created templates here
https://github.com/envless/envless/pull/94

**Comment by money8203** [comment]
Hey but you have added the issues template only and not the pull request !!!

**Comment by dahal** [comment]
@money8203 please go ahead 🙏🏼

**Comment by money8203** [comment]
#102 Done!
